### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by dvrkps** [2bytes/dodns#1]
Welcome to Go community. :smiley: 

Read this for more idiomatic code:

[Effective Go](https://golang.org/doc/effective_go.html)

[Go Code Review Comments](https://github.com/golang/go/wiki/CodeReviewComments)

d.

**Comment by hamid-elaosta** [comment]
@dvrkps Thank you. Both useful reading and will keep me occupied for a while :smile:

**Comment by hamid-elaosta** [comment]
Learned of `go vet` which helped find [this error](https://github.com/2bytes/dodns/blob/ca717352c51b34ce3121a624b4c02bfd7539a7cf/dodns_test.go#L129) in the tests when a string formatter directive is specified without the corresponding Errorf.

`go vet` documentation is: https://golang.org/cmd/vet/
